# Generated by Django 4.0.8 on 2022-10-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0015_user_address_user_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apicall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, unique=True)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('ISO2', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
