# Generated by Django 4.0.8 on 2022-10-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0016_apicall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='ISO2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
